apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticketing-tickets
  template:
    metadata: 
      labels:
        app: ticketing-tickets
    spec:
      containers:
        - name: ticketing-tickets
          image: gumberss/ticketing-tickets
          env:
            - name: NATS_CLIENT_ID
              valueFrom: 
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: MONGO_URI
              # It is only accessed inside of the cluster, 
              # so It won't be a problem to commit it 
              value: 'mongodb://ticketing-tickets-srv:27017/tickets' 
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: tickets-srv
spec:
  selector:
    app: ticketing-tickets
  ports:
    - name: tickets-port
      protocol: TCP
      port: 3000
      targetPort: 3000